### ISSUE TITLE
Auto complete not working

### ISSUE THREAD

**Issue by daryllocsinloke** [aziz/PlainTasks#134]
So I created keywords to make repeated words easy to re-type using auto complete

e.g.
stat_live
stat_pending

when I type say, stat_, then hit ctrl+space I am given the keywords...
upon selecting the desired word, nothing happened

**Comment by kirillsalykin** [comment]
i'm having similar issue, and main suspect is https://packagecontrol.io/packages/All%20Autocomplete.

**Comment by vovkkk** [comment]
IIRC, All Autocomplete breaks completions, i.e. you won’t see them by `ctrl+space` #153 

Also, I’m actually thinking that this issue is probably the same as  #185 so I close it.
