### ISSUE TITLE
Remove italic font type

### ISSUE THREAD

**Issue by rumpelsepp** [aziz/PlainTasks#137]
Hi,
I really like this plugin, but I hate reading my tasks in an italic font. I particularly do not get the reason why I should use an italic font type here. Using up to three different styles in one line does not improve the readability (see attached png).

![font](https://cloud.githubusercontent.com/assets/1961699/2604969/cb919438-bb3f-11e3-9ead-815bcbec02c9.png)

My suggestion:
- use a normal monospace font type for tasks
- use bold type for tags
- make done (canceled) tasks and annotations gray

**Comment by scott-joe-williams** [comment]
@rumpelsepp edit `~/Library/Application\ Support/Sublime\ Text\ 3/Packages/PlainTasks/tasks.hidden-tmTheme` as seen here https://github.com/scott-joe-williams/PlainTasks/commit/bd053820a2532b96e96b7aa1501aee8a38fb88a7

or just copy paste from my gist https://gist.github.com/scott-joe-williams/5cf2487b9d2dffe38927

**Comment by rumpelsepp** [comment]
:+1: 

In case other people read this: On Linux the path is: `~/.config/sublime-text-3/Packages/PlainTasks/tasks.hidden-tmTheme`

**Comment by amit-28** [comment]
what to change in that file? i changed all italic to plain, itried removing italic, nothing worked... please tell me what to change in tasks.hidden-tmTheme

**Comment by amit-28** [comment]
scott-joe both links are 404. please tell me on which lines to change in tasks.hidden-tmTheme to remove italic font. Thanx

**Comment by scott-joe** [comment]
@amit-28 sorry I changed my username so the links became "out of date" so to speak. And I deleted my PlainTasks fork. 

https://gist.github.com/scott-joe/5cf2487b9d2dffe38927 is basically the whole file if you want to just copy all of that into your version of the `tasks.hidden-tmTheme` file. Then you could do a `git diff` or just compare the two files in something like Kaleidoscope to see which lines were changed.

Hope that helps. Cheers!

**Comment by turkeyphant** [comment]
Anyone got working links for how to fix this?
