### ISSUE TITLE
Default settings symbols broken?

### ISSUE THREAD

**Issue by morkro** [aziz/PlainTasks#138]
Hello,

first of all you made a great job with this plugin! 
I installed it today, worked a few hours with it and everything went fine for me. After closing Sublime Text, rebooting my laptop and opening the project again your default symbols are broken/gone/i don't know. They can't be displayed. When I copy the symbols from your Readme on github they still can't be displayed. 

Maybe I have to mention that my .TODO is located in the projects folder. Can this cause the problem?

**Comment by djinpark** [comment]
Greetings:

For me, the symbols don't show up when I press cmd + enter or cmd + i. The checkbox only shows once, in the beginning of a new document opened with cmd + shift + p, task: new.
I checked the default setting and it was set correctly. 
I installed the app by copying it in packages folder. I use Mac OS X 10.10.3.

![screen shot 2015-06-20 at 8 41 52 am](https://cloud.githubusercontent.com/assets/7749633/8267294/b4d90348-1728-11e5-9c98-4fb9bcb09de7.png)

**Comment by vovkkk** [comment]
@veremeenko if it’s still an issue you should probably enable DirectWrite in ST settings `Preferences` → `Settings — User`: `"font_options": ["directwrite"	]`

@djinpark you seem enable Taskpaper compatibility if you did it by mistake then just disable it `Preferences` → `Package Settings` → `PlainTasks` → `Settings — User`: `"taskpaper_compatible": false`

**Comment by djinpark** [comment]
@vovkkk Thank you! I added it because the [readme](https://github.com/aziz/PlainTasks#taskpaper-compatibility) reads to add it without any explanation of its effect. I think it would be better if it explains what it does and its side effects.
