### ISSUE TITLE
Feature suggestion:  Code snippets with syntax highlighting support?

### ISSUE THREAD

**Issue by mkanet** [aziz/PlainTasks#152]
I usually use one generic Default.todo document for my general purpose note taking and todo tasks.  I'm if this is technically possible; but, it would be so nice to be able to define which SublimeText syntax highlighting to use for blocks of various code.  Being able to include that in our Todo Tasks would be extremely useful (if it's possible to do).  Maybe someone will consider on implementing something like this in PlainTasks:

**/C#**
//Iterate 0 - 4 elements in inventory variable:
for (int i=0; 1<3; i++)
    {
        inventory[i].print();
    }
Console.WriteLine("Done printing ")
**/C#**

or

**/JavaScript**
var os = require('os');
var message = 'This script is a running on Node.js ' + process.version + ' on a ' + os.type() + '-based operating system.';
console.log(message);
**/JavaScript**

**Comment by michaelmagistro** [comment]
I would second this feature and believe it deserves a second look. It makes the difference between having hundreds of random code files wandering around and being able to just embed small snippets in the task itself. even just having a fenced area which pops off all plaintasks syntax highlighting would be enough (no need to add syntax highlighting to the code block itself). it's when plaintasks treats code snippets as tasks (such as --comment in sql)
