### ISSUE TITLE
Feature feasibility:  Bold or Italicize selected text with hotkeys?

### ISSUE THREAD

**Issue by mkanet** [aziz/PlainTasks#169]
I really love the ability to bold-face or italicize any text I need to emphasize.  

I realize that SublimeText is not a word processor.  However, there is one *word-processor-like* capability that would make basic formatting very easy with using PlainTasks:

I'm just not sure if this is programmatically feasible (or too complex to implement); but, it would be so nice to be able to just conveniently highlight any string of text; then press the respective ST2/3 KeyBinding to convert the text to boldfaced or italicized.

Ultimately, if there could be two SublimeText Keybind-able Commands added:
**Tasks:** Boldface selected font
**Tasks:** Italicize selected text

**Comment by fredcallaway** [comment]
I disagree that this is invalid. There's no reason to make everyone do this independently. Other markdown editors have keybindings for italicization, so why shouldn't plain tasks?

**Comment by vovkkk** [comment]
PT is not Markdown.

The feature is so trivial, that initial message confused me so I’ve set invalid tag.

**Comment by fredcallaway** [comment]
Well done. I agree that treating `*` and `_`  like parens is the most sublime way to do this.
