### ISSUE TITLE
CMD+D adds space between @done and date

### ISSUE THREAD

**Issue by daftmilk** [aziz/PlainTasks#194]
When I hit CMD+D on an uncompleted task, it will correctly mark the task as done and add the time in brackets:

before and after:

```
☐ does tasks plugin for sublime add an extra space after the done tag? 
✔ does the update version from github have the same problem? @done (14-11-21 00:10)
```

I am using Brett Terpstra's gem doing. The space between _@done_ and _(14-11-21 00:10)_ breaks the time off the tag. I think this is wrong. How does taskpaper do this?

**Comment by EvanLovely** [comment]
Do you know why turning that setting on changes the look of completed tasks?

![2015-02-06 at 4 23 pm](https://cloud.githubusercontent.com/assets/569699/6089739/9b319196-ae1c-11e4-854a-c6018b1b22c3.png)

**Comment by vovkkk** [comment]
@EvanLovely because TaskPaper supports only certain bullet `-`, so when you enable compatibility PlainTasks forces those things that ensure compatibility, i.e. bullets, no space between done and date, only tab char for indenting etc.
