### ISSUE TITLE
Color scheme has stopped working

### ISSUE THREAD

**Issue by callumlocke** [aziz/PlainTasks#195]
For some reason my PlainTasks files have started appearing in my default colour scheme (the one I use for my code), as opposed to the original yellow/red/black colour scheme. I don't know what changed.

I tried uninstalling and reinstalling PlainTasks via Package Control, but this didn't fix it.

How can I re-enable the yellow color scheme for PlainTasks?

**Comment by owenleonard** [comment]
I had this same problem.  I found out if I close the TODO file and reopen it, then the color scheme started working correctly.  I had two TODO files open.  The one I closed and reopened responded to the color scheme changes, the other did not.  Restarting ST3 did not fix this.  Once I had reopened both TODO files, they both responded to the color scheme changes.  I'm not sure why restarting ST3 didn't make a difference.  Reinstalling PlainTasks also did not fix it (nor did disabling/enabling PlainTasks).

**Comment by vovkkk** [comment]
Alright then.

**Comment by binaryannie** [comment]
Thanks @owenleonard for the tip, it happened to me too!

I don't know if it can be of any help to find the cause of this but on reopening the file the console said:
```
reloading Packages/User/PlainTasks.sublime-settings
```

**Comment by farzher** [comment]
ty @owenleonard
I restarted and reinstalled things but it didn't help; simply closing and reopening the file fixed it
