### ISSUE TITLE
Only works with manual install of "PlainTasks-master"

### ISSUE THREAD

**Issue by pmaster** [aziz/PlainTasks#199]
The only way I can get PlainTasks to work at all now is to download the full zip file, unzip "PlainTasks-master", and copy that directly into my Packages directory. If I rename the folder "PlainTasks", even before or after moving it, it doesn't work. 

"Doesn't work" meaning there are no keyboard commands, no colour scheme, nothing. I've reinstalled both Sublime Text 2 and the Package Manager, as well as reinstalling PlainTasks six ways to Sunday, but this is the only way I can get it to function, and then with a ton of error messages about it being unable to find the colour scheme in the PlainTasks folder (because that folder doesn't exist):

    error: Error loading colour scheme Packages/PlainTasks/tasks.hidden-tmTheme: Error parsing plist xml: Failed to open file In file "Packages/PlainTasks/tasks.hidden-tmTheme"

**Comment by vovkkk** [comment]
I just remove PT and install it again via Package Control—all works on ST2. 
Sometimes restarting ST or re-opening a certain file (todo-list in this case) may eliminate troubles.


> error messages about it being unable to find the colour scheme in the PlainTasks folder (because that folder doesn't exist)

Did you, perhaps, copy default settings into user setting? so `color_scheme` points to non-existed folder.

All in all, I recommend close all todo-lists, remove all PT folders from Packages folder, install PT via PC, restart ST — I’m pretty sure it will do, thus close the issue, but let me know if there are still any troubles.
