### ISSUE TITLE
Feature Request: order tasks by due date

### ISSUE THREAD

**Issue by kirillsalykin** [aziz/PlainTasks#200]
It would be nice to see all pending tasks in chron order.
And i believe having "inbox" (tasks to be done today) will be valuable feature.

**Comment by vovkkk** [comment]
How you imagine it?
sort in place? separate tab? something else?

**Comment by kirillsalykin** [comment]
# Chron order
Separate tab will do the job.
Is it possible to change task in the separate tab and have it changed in the original place?

# Inbox section
I see inbox similar to "archive" section: additional section in the top, where copies of today tasks will be shown (with correspond project name). 

All changes will be applied to correspond tasks (kinda symlinks)

Is it possible? What do you think?

Also, it would be usefull to automatically add @today tag to today tasks (if today date matches @due()).
And @missed(not sure if it is right name? maybe @overdue?) if due date passed.

Thanks!

**Comment by BvanT** [comment]
Would love to see this feature

**Comment by shalecraig** [comment]
Ditto. This feature would be huge.
