### ISSUE TITLE
Feature Request: filter by tag (tags?)

### ISSUE THREAD

**Issue by kirillsalykin** [aziz/PlainTasks#201]
Also if it will work with chron ordering - it would be really awesome.
Thanks!

**Comment by vovkkk** [comment]
[Filter Lines](https://packagecontrol.io/packages/Filter%20Lines) does it, but given mention of chron ordering I think you mean something else?

**Comment by kirillsalykin** [comment]
Thanks for referencing Filter Lines package. Nice one.

But Filter Lines misses one important as for me feature - i cant edit task after filtering (changes wont be applied to the original task).

https://packagecontrol.io/packages/FindResultsApplyChanges - this works better, but it's not ideal.

Shall i ask Filter Lines to add "apply changes" possibility?

> but given mention of chron ordering I think you mean something else?
Sorry for not being clear I mean order by due date (if present)

Thanks.

**Comment by vovkkk** [comment]
Filter Lines has folding command, so everything stay in place and editable; I use custom keybinding:

```
{"keys": ["f3"], "command": "fold_to_lines", "args": {"search_type": "regex"}}
```

Anyway, let’s close it in favour of #200
