### ISSUE TITLE
Feature Request: add format of @wasted / @lasted

### ISSUE THREAD

**Issue by darkled** [aziz/PlainTasks#203]
For the moment `@wasted` / `@lasted` tags look like this:
```
 @lasted(10 days, 0:00)
```

It would be nice to have a possibility to change their formats in order to show, for example, only days without hour and minutes.

**Comment by vovkkk** [comment]
I don’t think it sould be another option, but code should be smarter (it’s already strip seconds if they equal to 00), especially if date format doesn’t include time `(%y-%m-%d)`

```
✔ @started(15-01-01) @done (15-01-10) @lasted(9 days, 0:00)
```

**Comment by darkled** [comment]
@vovkkk that would be even nicer.

**Comment by darkled** [comment]
@vovkkk Thanks, that's great!
