### ISSUE TITLE
Feature Request: Add custom hotkeys for tags

### ISSUE THREAD

**Issue by darkled** [aziz/PlainTasks#204]
It would be nice to have a possibility to assign any shortcut for own tag like it is done for `@started`, `@done`, etc.
E.g. I want to have additional `@review` tag. I add it to configuration and next time I need it I can press `r + tab` or `re + tab` or etc and get this tag on item.

**Comment by vovkkk** [comment]
You simply create file `Packages/User/PlainTasks.sublime-completions` like [this one](https://github.com/aziz/PlainTasks/blob/master/PlainTasks.sublime-completions):

```
{
"scope": "text.todo",
"completions": [
{ "trigger": "r\t@review", "contents": "@review"}
]
}
```

**Comment by darkled** [comment]
@vovkkk Thanks!

**Comment by warmwaffles** [comment]
This is actually awesome. Thanks for the snippet.
