### ISSUE TITLE
Feature Request: Extended functionality of tags / states

### ISSUE THREAD

**Issue by darkled** [aziz/PlainTasks#205]
For the moment all item actually have not so much states which are implemented as tags: `@started`, `@done`, `@canceled`. In my opinion it would be nice to have a possibility to customize each item's lifecycle with own states. Like if I want to have additional status `@review` between `@started` and `@done`.

Also would be nice to have any shortcut to easily switch between states. If an item has a lifecycle `@started`, `@review`, `@done`, we could go further on states with `ctrl + d`

**Comment by vovkkk** [comment]
dup #146
