### ISSUE TITLE
Feature Request: statistics by tags

### ISSUE THREAD

**Issue by darkled** [aziz/PlainTasks#207]
It would be nice to have more customized statistics by tags. Something like counting done or cancelled tasks tagged by `@tag`.

**Comment by vovkkk** [comment]
Do you have an idea about format?

I’m thinking `{{@tag}}` — i.e. double brackets define that word need to be searched
and output would be `7/10/0` — pending, completed, cancelled.
M?

**Comment by darkled** [comment]
@vovkkk I think it would be ok.

**Comment by darkled** [comment]
@vovkkk thanks! When will it be available in sublime's package control?

**Comment by vovkkk** [comment]
Usually their server pickup update in 15-60 minutes, then your local version may have cooldown due to recent autoupdate.
As far as I see server already [picked](https://packagecontrol.io/packages/PlainTasks) last version, so you may update localy by hand via command palette `Upgrade package`

**Comment by darkled** [comment]
@vovkkk great, thanks!
