### ISSUE TITLE
Cmd+Enter/Cmd+i should split task, when curser is in the middle of the task

### ISSUE THREAD

**Issue by walling** [aziz/PlainTasks#212]
Sometimes I want to refactor my tasks, for example splitting one task in two. It should be as easy as placing the cursor in the middle of the line and then pressing Cmd+Enter/Cmd+i (like you normally would split a line in two with just Enter).

Here is an example:

![Screenshot of PlainTasks with the cursor in the middle of a task line](http://i.imgur.com/DQbpa3s.png)

**Expected result:** When pressing Cmd+Enter/Cmd+i, I expect a new task created with “ and look at project schedule” in the new task and “Answer e-mails” in the current task. The cursor should be placed in the beginning of the new task.

**Actual result:** When pressing Cmd+Enter/Cmd+i, a new empty task is created under the current task and the cursor jumps to the end of the current line.

I'm not sure if it's a feature request or a bug, since the functionality of Cmd+Enter/Cmd+i is not very useful at the moment. Solving this issue could improve the ease of refactoring tasks.

**Comment by vovkkk** [comment]
This is exactly what Sublime Text does when you <kbd>⌘+enter</kbd> by default (except bullet), hence won’t fix.

But you can do it yourself, creating macro

```
[
	{ "command": "insert", "args": { "characters": "\n" }	},
	{ "command": "insert", "args": { "characters": "☐" }	},
	{ "command": "reindent" }
]

```

and adding custom keybinding into user’s file:

```
{
  "keys": ["super+enter"], 
  "command": "run_macro_file", 
  "args": {"file": "Packages/User/CreateNewTask.sublime-macro"}
  "context": [{ "key": "selector", "operator": "equal", "operand": "text.todo" }]
}
```
