### ISSUE TITLE
What was the default font?

### ISSUE THREAD

**Issue by hamid914** [aziz/PlainTasks#213]
I updated my OS X 10.9.5 to 10.10, and after reinstallation of Sublime Text 3 and PlainTasks, the default font for PlainTasks became "Consolas" and there is no font with this name in OS X, maybe it's for windows?
So what is the default font that is shown in the screenshot on this repository's homepage?

**Comment by aziz** [comment]
The default font and the font used in screenshot is **Consolas**. 
It's a really nice monospace font with a very beautiful and readable italic type. I highly recommend installing it on your Mac. I know Mac OSX does not ship consolas but it should not be hard to find on the web.
