### ISSUE TITLE
fullwidth forms input method support

### ISSUE THREAD

**Issue by medophin** [aziz/PlainTasks#214]
Sublime text 2 , OSX  , Using https://github.com/yahoo/keykey

1.  if i type a fullwidth text after creating a task , ex:  "☐\_！"   (\_ is a space)
    (fullwidth！ is typing by 'shift+1' then yahookeykey will allow you to choose a word,  press'enter'to confirm) After press enter , the word will disappear.

2. If i delete a space ' '  after☐ auto indent, ex:"☐！" , and typing '！' press enter   the word will display correctly.
3. If i copy and paste a fullwidth word , it will display correctly.

**Comment by edenyeh** [comment]
Same problems, who knows how to fix it?
And I use Traditional Chinese input methods in Mac OS X,
so, if I want to type fullwidth, I must change View-Syntax-Tasks to another one.
Thanks a lot~

**Comment by vovkkk** [comment]
Chinese is Greek for me (sorry for pun), so I didn’t know what to say previously.
Now, I made a little brainstorm, and I think [this](https://github.com/aziz/PlainTasks/blob/master/Default%20%28OSX%29.sublime-keymap#L10-L19) is the problem (can’t test, have no OSX, and on Windows it works somehow correctly, as far as I can judge w/o any knowledge in the language)

Try to add into `Preferences → Package Settings → PlainTasks → Settings - User`

       indent_after_task: false

so custom keybinding will be ignored.

**Comment by medophin** [comment]
You brainstorm is works! 
But i add into Preferences → Package Settings → PlainTasks → Settings - "default"
indent_after_task: false

It will pop-up some other error message, but it works! cheers.

**Comment by vovkkk** [comment]
Uh, well, in this case I’m going to remove this keybinding because it is probably third case when it cause problem, and besides it is just a keybinding which is not bound to any PT command and could be added into user file if anybody need it.
