### ISSUE TITLE
Inconsistent Indentation

### ISSUE THREAD

**Issue by CodeMonk** [aziz/PlainTasks#219]
I've noticed that indentation is sometimes off in my .todo files, and I've just discovered why.  I'm not sure if this is a bug, or by design, though:

Starting from a Project (it may happen elsewhere), go to the end of the line, and press enter:

    My Nice Project:<cursor here>

If you press enter, you get a nice 2 space indent:

    My Nice Project:
      Two space indent

If you press ctrl-enter (or ctrl-i / cmd-i), you get a one space indent:

    My Nice Project:
     ☐ One Space indent before checkbox
      Two space non-todo to show indentation issues.

Bug?  It certainly annoys me :)

**Comment by vovkkk** [comment]
You have to set into `Preferences → Package Settings → PlainTasks → Settings - User`:
```
"before_tasks_bullet_margin": 2
```

**Comment by CodeMonk** [comment]
Perfect!  Thanks for the pointer!
