### ISSUE TITLE
Separate Taskpaper compatibility from @done pre-date space

### ISSUE THREAD

**Issue by anatomatic** [aziz/PlainTasks#222]
I used `"before_date_space": false` in my PlainTasks.sublime-settings to keep @done(YYYY-MM-DD) next to each other. However a recent update seems to have deprecated `"before_date_space": false` and according to Issue #194 the new methodology is to use `taskpaper_compatable: true`, which forces strict use of `-` for bullets.

If there's anyway to re-enable the granular control of `"before_date_space": false` without breaking ✓ and ✘ bullets I'd appreciate it.

**Comment by vovkkk** [comment]
There was never such setting before.
Now you can remove space with
```json
"before_date_space": "" // empty string, not false, because it will be pasted directly
```

**Comment by anatomatic** [comment]
Thanks for correcting my error!
