### ISSUE TITLE
Make urls stand out less by making them themeable or a part of a tag

### ISSUE THREAD

**Issue by ronilaukkarinen** [aziz/PlainTasks#227]
Hi,

I sometimes include urls in my tasks and I was wondering could you make them stand out less, for example like this:

 	☐ Go to google @url → https://www.google.com

@url tag would be blueish (if it's possible to color certain tags differently) and the actual url with the arrow a low opacity grey, for instance. If you have lots of tasks with urls then the url is standing out too much when the task should be the real focus.

What do you think?

**Comment by vovkkk** [comment]
TBH, I think it is shame that ST doesn’t support urls out of the box.
Speaking of stand out, why not put url as note under task?

There was another [old] topic about delemiting urls which would make easier to add highlighting for them, anyway it is low priority for me.

**Comment by ronilaukkarinen** [comment]
Well, note is okay, but it doesn't make the task any more discreet and I tend to keep one task per line just for clearness sake. Yes, this is low priority. Just a thought to consider in the future.

**Comment by vovkkk** [comment]
Close it (see #88), i.e. it is themeable now.
