### ISSUE TITLE
FeatureRequest: move @today tasks to list on top

### ISSUE THREAD

**Issue by patmuk** [aziz/PlainTasks#228]
Hi,

it would be great if there would be a shortcut, similar to archive, which is moving all @today marked tasks to the top of the file, under a TODAY: project.

Btw: You guys wrote an amazing plugin!

**Comment by vovkkk** [comment]
Well, I understand your reasons, but _moving_ tasks has several disadvantages, most important is losing context permanently.

So why not use fold command from [FilterLines](https://github.com/davidpeckham/sublime-filterlines) plugin?
Or mine standalone app [Toway](https://github.com/vovkkk/Toway), which can show tasks from several files at once?

**Comment by patmuk** [comment]
Right, I see your point. It is different from archiving, where the context does not play a big role mostly.
Thanks for the two suggestions! They are both great! I will try them out - they should do the trick.

**Comment by jaimejim** [comment]
Someone should add this information to the tutorial. 

So why not use fold command from FilterLines plugin?
Filter With Regex ⌘+K ⌘+R

And so on...
