### ISSUE TITLE
Acrhive is not working ST2/ST3 (Windows)

### ISSUE THREAD

**Issue by slowpokefarm** [aziz/PlainTasks#230]
For some reason ctrl+shift+a just does nothing. I mean nothing at all. No confliting keybindings or anything else found, everything else works just fine.

**Comment by vovkkk** [comment]
Cannot reproduce.

See if there is any error in concole (View → Show Console).
Try to archive via command pallette, <kbd>ctrl+shift+p</kbd> `Tasks: Archive`
Try to create new file and see if archive works there.
Show me content of a file where archive doesn’t work, create [gist](https://gist.github.com/) and out link here.

**Comment by slowpokefarm** [comment]
Doesn't work in any file. I created a new one named 1.todo containing this

Project:
  [ ] 1
  [ ] 2
  [X] 33 @done (15-03-26 13:38)
  [X] 444 @done (15-03-26 13:39)
  [ ] 5555

didn't work.

**Comment by slowpokefarm** [comment]
UPD 

it worked after I set the bullet symbols to default

**Comment by vovkkk** [comment]
`[X]` is not valid bullet, these lines considered to be notes
`[x]` is valid done bullet (small x)
