### ISSUE TITLE
Reorder by Priority within a Project

### ISSUE THREAD

**Issue by sundarv85** [aziz/PlainTasks#231]
Hello

Inside a project, I have tasks with @critical and @high from the Priority list

```
Priority:
  ☐ type c, press tab key — it’ll become @critical
  ☐ type h, press tab key — it’ll become @high
  ☐ type l, press tab key — it’ll become @low
  ☐ type t, press tab key — it’ll become @today
```

It would be great if the tasks can get arranged under each Project based on this priority level as listed in the Tutorial.

Is that already possible?

**Comment by PixelT** [comment]
+1

**Comment by sundarv85** [comment]
Just pinging to check if any update is there on this. This would be really useful
