### ISSUE TITLE
Why is this Plug-In Opinionated?

### ISSUE THREAD

**Issue by SalvorinFex** [aziz/PlainTasks#232]
What types of opinions does it have?  
Does it critique your code?
Does it have opinions on world issues, like the poor and the hungry?
Does it belong to a political party and try to force you to see it's point of view?

**Comment by vovkkk** [comment]
Or maybe this plugin is conscious?
Does this plugin even do push ups?

All kind of questions! such interesting! wow mistirious! very plugin!
