### ISSUE TITLE
Consider HTML export instead of view

### ISSUE THREAD

**Issue by N4M3Z** [aziz/PlainTasks#240]
Please consider implementing HTML export from PlainTasks into a destination of user's choosing (i.e. not `/var/...`).

**Comment by vovkkk** [comment]
File is saved into default system temporary folder. The reason is that I’m not sure about reliability of conversion since it relies on ST scopes and `extract_scope` method is not really reliable, afic.

So it is recommended (by me, since conversion was written by me) to _preview_ html in browser, then save it from browser to whatever folder you want <kbd>ctrl+s</kbd> or whatever.

**Comment by N4M3Z** [comment]
I don't understand the harm caused by providing a simple export option next to the view option. The sole difference is in where the html file is saved.

**Comment by vovkkk** [comment]
I’m not against options, but conversion is a minor feature, each option increases overall complexity (complexity is bad).
Besides, there are some questions (most of which would be probably answered ‘add option’).

1. Should be html file saved in the same folder where original todo or another specific one?
2. If specific, should it be set in setting file or be choosen by user each time via dialog?
3. If not choosen by user, what to do in case of name conflict? overwrite or save with new generic name?
4. Should file, after it’s saved, be open in browser or not?

Currently, there is just one way, no options, and it does its job most of the time — simple.

**Comment by N4M3Z** [comment]
I don't think another option is necessary, I agree with your simplistic approach. I guess you could just open a save file dialog and leave the rest to the system. Depends if there are more people who would want this feature.

**Comment by reagle** [comment]
I just found this issue because I was wondering if PlainTasks made it easy to export the whole project and it's related links to HTML. (Like Zim Wiki does.) Apparently not?

**Comment by N4M3Z** [comment]
Well, the reasoning behind not including is feature is mentioned above. Personally, I think being able to set the output directory of the html file is just a natural extension of the current export feature. Perhaps if there is enough demand.

**Comment by vovkkk** [comment]
Export the whole projects means many todo files?
If so, then current implementation is not suitable for this, it depends on view object which means it need todo list being open in ST tab (including unsaved).
If you can and want to write proper parser, please, do so.

**Comment by vovkkk** [comment]
Asking for output folder may be clunky, seems not possible to do it directly, instead we can open new view insert html and close view, ST will ask if you want to save it. If it is what you want @N4M3Z (not mobile-friendly nickname, btw  😊 ) I can do it.

**Comment by N4M3Z** [comment]
@vovkkk Most satisfactory! Thank you.
