### ISSUE TITLE
Bug, { done_tag: false } adds spaces to end of tasks when toggled

### ISSUE THREAD

**Issue by nfour** [aziz/PlainTasks#241]
To replicate set `done_tag: false` in the user settings, then try Ctrl+D toggling a task. 2 Spaces will be added to the end every time. This is annoying as fuck when you have wordwrap enabled.

**Comment by vovkkk** [comment]
Please, don’t drop f-bombs here.

**Comment by nfour** [comment]
Thansk ;)
