### ISSUE TITLE
Define default scheme in user-settings file.

### ISSUE THREAD

**Issue by dubeg** [aziz/PlainTasks#242]
Could it be possible to remove the scheme defined in the default settings file, and instead create a user settings file at the plugin's first run, and define the scheme there instead?

The reason I'd like this is so I can conveniently remove the plugin's default scheme, so that it won't override the scheme defined in Preferences.

**Comment by vovkkk** [comment]
If you use PC3 you can use its API to change you settings on `events.post_upgrade("PlainTasks")`  https://packagecontrol.io/docs/events

We won’t do it since some users may be still using older PC.
