### ISSUE TITLE
Unable to zoom into tasks (as per usual)

### ISSUE THREAD

**Issue by fgimian** [aziz/PlainTasks#243]
Hey there, really great extension :smile: 

I often use Ctrl + and Ctrl - (or Ctrl + scroll) to zoom in and out of Sublime Text but these shortcuts don't work when I'm editing a PlainTasks file.

Would this be hard to re-enable?

Thanks!
Fotis

**Comment by simonini** [comment]
+1

**Comment by fgimian** [comment]
I found the problem (which was mentioned in https://github.com/aziz/PlainTasks/pull/186)

The solution seems to be to comment out the font_size in the default settings of PlainTasks as it overrides the application-wide settings:

```
  // "font_size": 11,
```

I can't seem to find a way to override it to disable it, so it seems that this is the only option.  It's not ideal since any update of the extension will overwrite this file.

Devs, would you kindly consider not setting the font size in the default config as it is rather bad for consistency and accessibility for those of us without perfect eyes who often need to zoom in :smile:

**Comment by aziz** [comment]
I'm ok with commenting out the `font_size`. 
Let's keep this discussion open for a couple of weeks though for others to chip in.

**Comment by fgimian** [comment]
Thanks @aziz, really appreciate your help and time on this

**Comment by fgimian** [comment]
Thank you so much for this, means a lot!! :smile:
