### ISSUE TITLE
Color scheme does not load up

### ISSUE THREAD

**Issue by ronilaukkarinen** [aziz/PlainTasks#245]
After not using PlainTasks for some time I just noticed color schemes are not loading up properly. Just did a clean PlainTasks reinstall and result is this no matter what theme is in use:

![](http://i.imgur.com/20cWu4I.png "Screenshot")

What's causing this?

**Comment by norlin** [comment]
I have the same bug for few days (not sure when & why it was happened). Plugin re-install didn't helped. ST3 build 3083.

**Comment by vovkkk** [comment]
Do you use Color Highlighter?
If yes, disable it `Preferences → Settings — User`:

```
"ignored_packages":
	[
		"Color Highlighter",
		"Vintage"
	]
```

**Comment by norlin** [comment]
Lol, it helped. But why? :) Is it bug in Color Highlighter or in Plain Tasks?

**Comment by ronilaukkarinen** [comment]
That did the trick, yes. But naturally my color underlays are not working... I would like to know the same than @norlin, is it a bug in Color Highlighter or Plain Tasks?

**Comment by vovkkk** [comment]
> Is it bug in Color Highlighter

https://github.com/Monnoroch/ColorHighlighter/issues/244

**Comment by ronilaukkarinen** [comment]
Right. Thanks for referencing the issue.
