### ISSUE TITLE
Inconsistent date completion format

### ISSUE THREAD

**Issue by Zeeker** [aziz/PlainTasks#248]
Hey guys,

I've noticed some inconsistencies when using the completion of dates. Let's get straight to it:
## Examples:

**Settings (User)**   

```
{
    "date_format": "(%d-%m-%y %H:%M)"
}
```

`@due(+1)` <kbd>tab</kbd>  
**Expected:** `@due(08-09-15 10:20)`
**Received:** `@due(08-09-15 10:20)`

This is correct, however when I do this:

`@due(08-09-2015)` <kbd>tab</kbd>  
**Expected:** `@due(08-09-15 10:20)`
**Received:** `@due(15-09-08 10:20)`

As you can see, my custom date format will be ignored when I try to complete a short date. If you need any further information don't hesitate to ask.

**Comment by vovkkk** [comment]
It is not a bug, but I’d agree to consider it as a flaw.

First, I recommend to re-read readme about this feature.
Second, what is going on? Short format (one you expand) is `year-month-day hour:minutes`, `year` & `month` are optional, so when you got three numbers it is interpreted as `year-month-day`.
If you actually expand `08-09-2015` you should get error message:
![2015-09-07 19-08-20 sublime text](https://cloud.githubusercontent.com/assets/1975298/9717341/d28dc154-5593-11e5-9396-db649dbe5f06.png)

If you expand `08-09-15` then you get this date _exactly_ in your custom format.
