### ISSUE TITLE
Feature Request: Flexible Date Customization

### ISSUE THREAD

**Issue by jemhuntr** [aziz/PlainTasks#250]
There's nowhere in the README nor tutorials that say anything about date formatting. Moreover, the date modifiers currently don't follow any known standard. It would be nice if we could format the date with more comprehensive options like [this](http://php.net/manual/en/function.date.php) or [this](https://ellislab.com/expressionengine/user-guide/templates/date_variable_formatting.html).

**Comment by vovkkk** [comment]
Does the C standard (1989 version) not being consider as ‘known’? :neckbeard: kids these days

PT uses Python datetime module, docs for [ST2](https://docs.python.org/2.6/library/datetime.html#strftime-and-strptime-behavior), for [ST3](https://docs.python.org/3.3/library/datetime.html#strftime-and-strptime-behavior).

**Comment by jemhuntr** [comment]
Oh, sorry about that, and thanks. I haven't actually encountered the C standard before :(

Although it would still be nice if these links would be provided at least on the README, for more clarity.
