### ISSUE TITLE
Highlighting custom tags

### ISSUE THREAD

**Issue by alexandre-f-ouellette** [aziz/PlainTasks#252]
I have created custom tags (e.g. @user).
Is it possible to set the highlighting for custom tags?

A bit like the @critical and @high tags.

Thanks

**Comment by vovkkk** [comment]
Short answer: no.

For highlighting there must be two things
1) definition in tmLanguage file of what to highlight
2) definition in tmTheme file of how to highlight

You can modify those files by hand, but make it automatically is close to impossible, afaik.

**Comment by alexandre-f-ouellette** [comment]
Perfect, thanks!

I'll play with it by hand.

**Comment by vovkkk** [comment]
Oh, bad news is that if PT will be updated by Package Control then your changes will be lost.
You can save tmTheme in `Packages/User` and set its path in PT user settings file.
But tmLanguage, I don’t know; you probably should make back up or something.
