### ISSUE TITLE
HTML View Color Scheme

### ISSUE THREAD

**Issue by NJBS** [aziz/PlainTasks#255]
Currently the HTML view will use the default color scheme when generating an HTML preview regardless of what your user-defined color scheme is.

**Comment by vovkkk** [comment]
HTML is based on template https://github.com/aziz/PlainTasks/blob/master/templates/template.html

You can edit your local version to change CSS (do not forget to back your changes up).


It would be cool to make CSS on the fly based on colour scheme, but it is not trivial and I’m very busy at least until next year, so feel free to send pull request if you will.








От: NJBS
Отправлено: ‎четверг‎, ‎12‎ ‎ноября‎ ‎2015‎ г. ‎12‎:‎54
Кому: aziz/PlainTasks





Currently the HTML view will use the default color scheme when generating an HTML preview regardless of what your user-defined color scheme is.

**Comment by jaimejim** [comment]
+1
