### ISSUE TITLE
Taskpaper compatible

### ISSUE THREAD

**Issue by jaapnoordzij** [aziz/PlainTasks#259]
I alternate between Taskpaper and your Sublime Plugin however I found that PlainTasks messes up my Taskpaper format. By looking at the source I found that there is a "taskpaper_compatible" setting. I am using that now and all my problems are gone. Thanks.

Please add it to the "default settings" because I think it is not documented.

**Comment by vovkkk** [comment]
It is documented in [readme](https://github.com/aziz/PlainTasks#taskpaper-compatibility) as well as several other settings.
Default setting file is an example, it don’t need contain everything.

**Comment by jaapnoordzij** [comment]
Thank you !
