### ISSUE TITLE
Bug: Tag completion rules not working, nor list of them.

### ISSUE THREAD

**Issue by Luchillo** [aziz/PlainTasks#261]
Any of the type `ctrl + space`or the tab completion for tags like `due` or `created` works.

**Comment by vovkkk** [comment]
Does <kbd>ctrl+space</kbd> work in any other filetypes? python, js, html, others?
What version of ST you use?
Which other plugins you use? esp. those related to autocomplete.

**Comment by Luchillo** [comment]
Not at all, wrong key binding?

**Comment by vovkkk** [comment]
Well, maybe if you on Linux then it should be <kbd>alt+/</kbd>, but it doesn’t explain why <kbd>tab</kbd> doesn’t work.

Try to use [FindKeyConflicts](https://packagecontrol.io/packages/FindKeyConflicts)

**Comment by Luchillo** [comment]
Wow that's a long list, which one should i look, `ctrl + space` i guess.

**Comment by vovkkk** [comment]
Whatever keybinding which doesn’t work. 
First of all, `[tab]`.
Then, `[crtl+space]` (if you’re on Windows or OSX) or `[alt+/]` (if you’re on Linux).

Please, post results for these keybindings here.

**Comment by Luchillo** [comment]
Ok i'm on linux so `[alt + /]` works, didn't find the tab in conflicts

**Comment by vovkkk** [comment]
> didn't find the tab in conflicts

I’m confused, does tab key works as expected or not?

Here is what I got:

```
 [tab]
   insert_best_completion                   Default               
   insert_best_completion                   Default               [{"operator": "equal", "operand": true, "key": "setting.tab_completion"}]
   replace_completion_with_next_completion  Default               [{"operator": "equal", "operand": "insert_best_completion", "key": "last_command"}, {"operator": "equal", "operand": true, "key": "setting.tab_completion"}]
   reindent                                 Default               [{"operator": "equal", "operand": true, "key": "setting.auto_indent"}, {"operator": "equal", "operand": true, "match_all": true, "key": "selection_empty"}, {"operator": "regex_match", "operand": "^$", "match_all": true, "key": "preceding_text"}, {"operator": "regex_match", "operand": "^$", "match_all": true, "key": "following_text"}]
   indent                                   Default               [{"operator": "regex_contains", "operand": "\n", "key": "text"}]
   next_field                               Default               [{"operator": "equal", "operand": true, "key": "has_next_field"}]
   commit_completion                        Default               [{"key": "auto_complete_visible"}, {"key": "setting.auto_complete_commit_on_tab"}]
   dired_complete                           FileBrowser           [{"operand": true, "key": "setting.dired_prompt"}]
   plain_task_insert_date                   PlainTasks            [{"operator": "equal", "operand": true, "match_all": true, "key": "selection_empty"}, {"operator": "equal", "operand": "text.todo", "key": "selector"}, {"operator": "regex_contains", "operand": "(@started|@toggle|@created)(?!\\([\\d\\w,\\.:\\-/ @]*\\))", "match_all": true, "key": "preceding_text"}]
   plain_tasks_replace_short_date           PlainTasks            [{"operator": "equal", "operand": true, "match_all": true, "key": "selection_empty"}, {"operator": "equal", "operand": "text.todo", "key": "selector"}, {"operator": "regex_contains", "operand": "@due\\([^\\)]+(?!.*?\\))", "match_all": true, "key": "preceding_text"}, {"operator": "regex_contains", "operand": "[ \t]*\\)", "match_all": true, "key": "following_text"}]
   smart_folding                            SmartMarkdown         [{"operator": "equal", "operand": "markup.heading.markdown", "key": "selector"}]
   smart_table                              SmartMarkdown         [{"operator": "equal", "operand": "text.html.markdown", "key": "selector"}, {"operator": "regex_contains", "operand": "^\\s*(\\||\\+[-=])", "match_all": true, "key": "preceding_text"}]
   smart_table                              SmartMarkdown         [{"operator": "equal", "operand": "text.html.markdown", "key": "selector"}, {"operator": "regex_contains", "operand": "^\\s*", "key": "preceding_text"}, {"operator": "regex_contains", "operand": "\\s*(\\||\\+[-=])", "match_all": true, "key": "following_text"}]
   next_field                               User                  [{"operator": "equal", "operand": "insert_best_completion", "key": "last_command"}, {"operator": "equal", "operand": true, "key": "has_next_field"}]
   insert_best_completion                   User                  [{"operator": "equal", "operand": "insert", "key": "last_command"}, {"operator": "equal", "operand": true, "match_all": false, "key": "selection_empty"}, {"operand": false, "key": "setting.dired_prompt"}]
```

**Comment by Luchillo** [comment]
Sorry, my bad, here it is:
>     [tab]
     insert_best_completion                   Default               
     insert_best_completion                   Default               [{"operator": "equal", "operand": true, "key": "setting.tab_completion"}, {"operator": "regex_match", "match_all": true, "operand": ".*[^0-9]$", "key": "preceding_text"}]
     replace_completion_with_next_completion  Default               [{"operator": "equal", "operand": "insert_best_completion", "key": "last_command"}, {"operator": "equal", "operand": true, "key": "setting.tab_completion"}]
     reindent                                 Default               [{"operator": "equal", "operand": true, "key": "setting.auto_indent"}, {"operator": "equal", "match_all": true, "operand": true, "key": "selection_empty"}, {"operator": "regex_match", "match_all": true, "operand": "^$", "key": "preceding_text"}, {"operator": "regex_match", "match_all": true, "operand": "^$", "key": "following_text"}]
     indent                                   Default               [{"operator": "regex_contains", "operand": "\n", "key": "text"}]
     next_field                               Default               [{"operator": "equal", "operand": true, "key": "has_next_field"}]
     commit_completion                        Default               [{"key": "auto_complete_visible"}, {"key": "setting.auto_complete_commit_on_tab"}]
     insert_dimensions                        AutoFileName          [{"key": "setting.auto_complete_commit_on_tab"}, {"operator": "equal", "operand": true, "key": "auto_complete_visible"}, {"operator": "equal", "operand": true, "key": "afn_insert_dimensions"}]
     bh_next_wrap_sel                         BracketHighlighter    [{"operator": "equal", "match_all": true, "operand": true, "key": "bh_wrapping"}]
     jsdocs                                   DocBlockr             [{"operator": "equal", "match_all": true, "operand": true, "key": "setting.auto_indent"}, {"operator": "equal", "match_all": true, "operand": true, "key": "selection_empty"}, {"operator": "equal", "match_all": true, "operand": false, "key": "auto_complete_visible"}, {"operator": "regex_contains", "match_all": true, "operand": "^\\s*(\\/\\*|###)[*!]\\s*$", "key": "preceding_text"}]
     insert_snippet                           DocBlockr             [{"operator": "equal", "match_all": true, "operand": true, "key": "selection_empty"}, {"operator": "regex_contains", "match_all": true, "operand": "^\\s*\\/\\*$", "key": "preceding_text"}]
     jsdocs_indent                            DocBlockr             [{"operator": "equal", "match_all": true, "operand": true, "key": "setting.jsdocs_deep_indent"}, {"operator": "equal", "match_all": true, "operand": true, "key": "setting.auto_indent"}, {"operator": "equal", "match_all": true, "operand": true, "key": "selection_empty"}, {"operator": "regex_contains", "match_all": true, "operand": "^\\s*\\*\\s*$", "key": "preceding_text"}, {"operator": "equal", "match_all": true, "operand": "comment.block", "key": "selector"}]
     expand_abbreviation_by_tab               Emmet                 [{"operator": "equal", "match_all": true, "operand": "source.css, source.sass, source.less, source.scss, source.stylus, source.jade, text.jade, text.slim, text.xml, text.html - source, text.haml, text.scala.html, source string", "key": "selector"}, {"operator": "not_equal", "match_all": true, "operand": "storage.type.templatetag.django", "key": "selector"}, {"match_all": true, "key": "selection_empty"}, {"operator": "equal", "match_all": true, "operand": false, "key": "has_next_field"}, {"operator": "equal", "match_all": true, "operand": false, "key": "setting.disable_tab_abbreviations"}, {"operator": "equal", "match_all": true, "operand": false, "key": "auto_complete_visible"}, {"match_all": true, "key": "is_abbreviation"}]
     expand_abbreviation_by_tab               Emmet                 [{"operator": "equal", "match_all": true, "operand": "source.css, source.sass, source.less, source.scss, source.stylus, source.jade, text.jade, text.slim, text.xml, text.html - source, text.haml, text.scala.html, source string", "key": "selector"}, {"operator": "not_equal", "match_all": true, "operand": "storage.type.templatetag.django", "key": "selector"}, {"match_all": true, "key": "selection_empty"}, {"operator": "equal", "match_all": true, "operand": false, "key": "has_next_field"}, {"operator": "equal", "match_all": true, "operand": true, "key": "auto_complete_visible"}, {"operator": "equal", "match_all": true, "operand": false, "key": "setting.disable_tab_abbreviations_on_auto_complete"}, {"match_all": true, "key": "is_abbreviation"}]
     run_macro_file                           MarkdownEditing       [{"operator": "equal", "operand": true, "key": "setting.auto_match_enabled"}, {"operator": "equal", "match_all": true, "operand": true, "key": "selection_empty"}, {"operator": "regex_contains", "match_all": true, "operand": "\\*$", "key": "preceding_text"}, {"operator": "regex_contains", "match_all": true, "operand": "^\\*", "key": "following_text"}, {"operator": "equal", "match_all": true, "operand": "text.html.markdown", "key": "selector"}, {"operator": "not_equal", "match_all": true, "operand": "markup.raw", "key": "selector"}]
     indent_list_item                         MarkdownEditing       [{"operator": "equal", "match_all": true, "operand": true, "key": "selection_empty"}, {"operator": "regex_contains", "match_all": true, "operand": "^\\s*(>\\s*)?[*+\\-]\\s+$", "key": "preceding_text"}, {"operator": "regex_contains", "match_all": true, "operand": "^$", "key": "following_text"}, {"operator": "equal", "match_all": true, "operand": "text.html.markdown", "key": "selector"}, {"operator": "not_equal", "match_all": true, "operand": "markup.raw", "key": "selector"}]
     indent_list_multiitem                    MarkdownEditing       [{"operator": "equal", "match_all": true, "operand": false, "key": "selection_empty"}, {"operator": "equal", "match_all": true, "operand": "text.html.markdown", "key": "selector"}]
     complete_underlined_header               MarkdownEditing       [{"operator": "equal", "match_all": true, "operand": "text.html.markdown", "key": "selector"}, {"operator": "equal", "match_all": true, "operand": true, "key": "selection_empty"}, {"operator": "equal", "match_all": true, "operand": false, "key": "auto_complete_visible"}, {"operator": "regex_contains", "match_all": true, "operand": "^\\-+$|^\\=+$", "key": "preceding_text"}, {"operator": "not_equal", "match_all": true, "operand": "markup.raw", "key": "selector"}]
     plain_task_insert_date                   PlainTasks            [{"operator": "equal", "match_all": true, "operand": true, "key": "selection_empty"}, {"operator": "equal", "operand": "text.todo", "key": "selector"}, {"operator": "regex_contains", "match_all": true, "operand": "(@started|@toggle|@created)(?!\\([\\d\\w,\\.:\\-/ @]*\\))", "key": "preceding_text"}]
     plain_tasks_replace_short_date           PlainTasks            [{"operator": "equal", "match_all": true, "operand": true, "key": "selection_empty"}, {"operator": "equal", "operand": "text.todo", "key": "selector"}, {"operator": "regex_contains", "match_all": true, "operand": "@due\\([^\\)]+(?!.*?\\))", "key": "preceding_text"}, {"operator": "regex_contains", "match_all": true, "operand": "[ \t]*\\)", "key": "following_text"}]

**Comment by vovkkk** [comment]
Open console (View → Show Console) and run `sublime.log_commands(True)`, then try use tab key with `@due`. 
What output is in console?

**Comment by Luchillo** [comment]
This is the output:
>command: insert_best_completion {"default": "	", "exact": false}

**Comment by vovkkk** [comment]
I’ve expected to see two commands, since you supposed to press tab twice: d, tab, tab.

However, if it will show the same output twice, then try to copy two keybindings for tab from default PlainTasks’ keybindings file to your user’s keybindings file.

**Comment by Luchillo** [comment]
Ah maybe it's because i have completion with `tab` instead of `enter`?

**Comment by Luchillo** [comment]
When i try to do the completion, since i do it with tab, doing `d then tab` auto-completes to data, that's why i don't do the second one, i didn't even notice i needed to hit twice the tab.
