### ISSUE TITLE
How do I find all my plaitask files?

### ISSUE THREAD

**Issue by jayeshjain24** [aziz/PlainTasks#266]
Okay, I wrote my to do list and now I have lost it. Can any body tell me how to open those .TODO files or where can I get them?

I forgot the name of the file and not able to find it now. Any help??

**Comment by vovkkk** [comment]
Can you use search? I mean any OS has this functionality.
Also, if you you’re on Windows try [Everything](https://www.voidtools.com/) (search by filenames) or [Rummage](https://github.com/facelessuser/Rummage) (search by contents).

**Comment by jayeshjain24** [comment]
I am on UBUNTU and I searched for all the files with .TODO,I didnt find any.

**Comment by vovkkk** [comment]
> I didnt find any

Even [tutorial](https://github.com/aziz/PlainTasks/blob/master/messages/Tutorial.todo)?

Try `find` command in terminal:

```
find ~ -iname '*todo*'
```
