### ISSUE TITLE
Open file in external application

### ISSUE THREAD

**Issue by mrvkino** [aziz/PlainTasks#267]
It would be nice to be able to specify a file to open in a external application. I put a lot of path to pdf spec in my task file. We could use the regular file link but append a "file:" first and let the os figure it out.

The line: `[[file:<path to pdf>]]` would become `open <path to pdf>` on the command line in osx.

**Comment by vovkkk** [comment]
You may get it using url syntax `<full path to pdf>`

**Comment by mrvkino** [comment]
Didn't seem to work, but I found a sublime package [non text mode](https://packagecontrol.io/packages/Non%20Text%20Files) that opens binary file with another application. With this, a `[[<path to pdf>]]` open in preview instead of sublime.

I'll close it since a package does the correct behaviour with this one.

**Comment by vovkkk** [comment]
> Didn't seem to work

What do you mean? open urls with different keys than file links, do you use correct keys?
Or it does not work like browser ‘download’ that file? or what?

**Comment by mrvkino** [comment]
I tried using `file://hostname/<path to pdf>` (with hostname, 127.0.0.1, without hostname) and the bare `/path/to/pdf` using the open url and open file command of plaintask. I also tried with and without the `[[ ]]`. None of them worked. The open url didn't do anything (I had a message: there is nothing to open), the open file always opened the pdf in sublime (except when the file://hostname was added).

**Comment by vovkkk** [comment]
It seems you misunderstood me about `<full path to pdf>`:

![2016-03-23 09-40-13 untitled notes-md - sublime text](https://cloud.githubusercontent.com/assets/1975298/13975019/65c93f6a-f0db-11e5-91d9-577ec573abfd.png)

But anyway it does not work with file in ST3, and opens http in IE despite I have Fx as default, same issue in stand-alone Python 3.5. But all work correctly in ST2. godamithatethatpy3 :confused:
