### ISSUE TITLE
Feature: Highlight tasks that are past their due date

### ISSUE THREAD

**Issue by fredcallaway** [aziz/PlainTasks#276]
The highlighting would be done in the same way that linters do it.

I'm willing to take on this project if there is indication that it would be pulled if implemented correctly.

One could also run a user defined script when a task hits it's due date (or some time before).

**Comment by vovkkk** [comment]
> I'm willing to take on this project if there is indication that it would be pulled if implemented correctly.

Sure.

**Comment by martinsam** [comment]
+1

**Comment by BvanT** [comment]
+1

**Comment by fredcallaway** [comment]
I got it working on my own machine but ran into trouble with dependence on dateutil. Since then, I've moved to Checkvist because I think a mobile interface is critical for a to-do list.

Here's what I had if someone wants to try to get it working:

https://gist.github.com/fredcallaway/ffdf31d6a51c881d9be6f3a1d6784c6a
