### ISSUE TITLE
Open File Command (Alt-o)

### ISSUE THREAD

**Issue by BWBob** [aziz/PlainTasks#280]
I am using Sublime Text 3 on a Win 7 machine.  When I try to use the open file key binding, it does not open the file.  Instead it adds the parent directory of the file to the active project.  Since that directory is already in the project, it effectively adds an additional link.  No file open activity or open directory activity is done.  Obviously there is a configuration conflict somewhere.  Any suggestions?

This is a very powerful part of the package which I really need for my workflow so hope I can get it to work. 

thanks

**Comment by vovkkk** [comment]
I cannot reproduce on Windows8.1.

What is build number? Help→About, we support only 2221, 3114, 3118 currently.
What is path of a file? how you create link?

**Comment by BWBob** [comment]
I am using build number 3114.
The file path is

.\Paper_Projects.txt

I restarted (something I did several times previously) and it is now giving me the following error:

"line does not contain valid link to file"

**UPDATE:  I inserted an ending backslash and it now works.  I misread the tutorial.**

thanks for the rapid assist.

BWBob

**Comment by vovkkk** [comment]
Ending [back]slash is mandatory for supporting white-spaces in paths, and mixing link with regular text on the same line.

If you say it works, then issue should be closed.
