### ISSUE TITLE
Maintaining indentations when archiving tasks

### ISSUE THREAD

**Issue by jontas** [aziz/PlainTasks#282]
I've seen a few issues that touch on a similar topic (#69 and #82) but none that request this explicitly:

When archiving a task that has completed sub tasks, it would be nice if the archive maintained the indentation.

In my workflow, main tasks usually correspond to line items I will put on invoices, and sub tasks are for my own planning/information/tracking.  Therefore, when preparing an invoice, it is necessary for me to know the total time spent on a task, meaning, the sum of all its sub tasks.  Right now this requires tracking time on both the main task and the sub tasks, or going through the archive and figuring out which tasks go with which.  If the indentation was maintained when archiving it would solve this problem.

Thanks!

**Comment by vovkkk** [comment]
You can archive block into another file:

><kbd>⌘ + shift + o</kbd> will archive in Org-Mode style, removing the entire subtree after cursor and appending it to new file next to original one, e.g. if original is `filename.TODO` then new would be `filename_archive.TODO`

Is it not enough?

**Comment by jontascher-ae** [comment]
I did not realize that archiving in a new file preserved the indentation, I assumed it worked the same way as same-file archives.  This is a good solution, thanks!

**Comment by vovkkk** [comment]
The word subtree in docs was supposed to hint that indents are preserved. Feel free to suggest better wording, if you will.



> This is a good solution

Alright, I close it then.
