### ISSUE TITLE
can I stop Clicking bullet with left mouse button toggles done and pending modes?

### ISSUE THREAD

**Issue by kudoshinji** [aziz/PlainTasks#284]
Clicking bullet with left mouse button toggles done and pending modes.
Is there any setting to stop this,i always make mistakes.

**Comment by vovkkk** [comment]
There is no setting, but you can redefine click in `Packages/User/Default.sublime-mousemap`:

```js
[{"button": "button1", "count": 1,"press_command": "drag_select"}]
```

**Comment by aziz** [comment]
@vovkkk let's revert this click feature. it's causing more harm than good. I've requested SublimeHQ to add a context key to their mouse command mapping, but until then adding any mouse interaction is causing more problems for the users when dealing with other files.

**Comment by vovkkk** [comment]
@aziz I’m surprised; what harm it’s causing? with other files? I don’t see any problems.

**Comment by aziz** [comment]
1. it's global. it means that we're overriding anyone else who defined this mouse command, or someone else is gonna override us. and we have no control over it.
2. It's firing everywhere, even on files that's not related to PlainTasks. it's just not a good practice that'll cause more issues in the future.
