### ISSUE TITLE
Quick add new date as jernl

### ISSUE THREAD

**Issue by Kristinita** [aziz/PlainTasks#286]
Hello. In [jernl](https://github.com/jasongardnerlv/jernl) plugin there is a possibility of fast addition of new date.

![Jernl new date](http://i.imgur.com/POQnp7H.gif)

Whether it is possible to carry out similar in PlainTasks? That it was quickly possible to add since a new line `25/08/2016:` , `26/08/2016:` and so on?

Thanks.

**Comment by vovkkk** [comment]
Try [InsertDate](https://packagecontrol.io/packages/InsertDate), it works in any views/files.

If you mean something different, please, elaborate (можно по-русски, если удобнее).
