### ISSUE TITLE
fold to show @due items

### ISSUE THREAD

**Issue by iProcrastinate** [aziz/PlainTasks#288]
Hi,

The highlighting of past, soon and invalid tasks is very helpful but it would be really good to have a way of folding the document to just leave tasks that are not done and that are due up to and including today. The Filter Lines package is very useful for folding based on a regex but it is not easy to use this to interpret the dates in the @due tag. Many thanks.

**Comment by vovkkk** [comment]
> due up to and including today

I don’t understand what `due up to` means.

**Comment by iProcrastinate** [comment]
Sorry I meant any tasks marked with a due tag dates today or before today

**Comment by vovkkk** [comment]
So, in the other words those tags which highlighted as past or soon, but not invalid or future.

**Comment by iProcrastinate** [comment]
Yes exactly! That would be really useful as a hot key, effectively a todo for the day that could be edited and would save to the document as a whole.
