### ISSUE TITLE
Not all user settings are applying

### ISSUE THREAD

**Issue by jaacob** [aziz/PlainTasks#289]
OS X 10.11.6, ST3 3124, PlainTasks 9/19 release.

My chosen theme stopped being applied to Tasks docs, and which settings file is being applied seems inconsistent.

`Preferences > Package Settings > PlainTasks > Settings - Default` opens a doc `PlainTasks (OSX).sublime-settings` from `Packages/PlainTasks/`. There are no non-OS-specific `.sublime-settings` files in that directory.

`Preferences > Package Settings > PlainTasks > Settings - User` opens a doc `PlainTasks.sublime-settings` from `Packages/User/`.

Some of the settings in the `Settings - User` file change the appearance/functionality of open Tasks documents, but some settings don't take.

**For example:**

- Changing `font_size` and `font_face` works fine—I can trump the config with new values in `Settings - User`, even when I leave the `Settings - Default` setting alone (active, not commented out).
- Changing the theme doesn't work. (It's "stuck" on one theme, no matter if I change it in the User or Default file, or both.)
    - In Default, I have `"color_scheme": "Packages/PlainTasks/tasks-solarized-light.hidden-tmTheme"`
    - In User, I have `"color_scheme": "Packages/User/PlainTasks/tasks-solarized-light.hidden-tmTheme"`
    - The doc is not using solarized-light. Even after rebooting ST3, and rebooting the computer. I have verified that the theme file is in both locations.

How do I debug this?

**Comment by vovkkk** [comment]
Did you try to reopen the doc?
Is the doc a file or unsaved view?

**Comment by jaacob** [comment]
The doc is a existing saved file, and has been saved while open.

Closing and reopening the doc (but **not** Sublime Text itself) fixed it. Kind of odd that some changes apply hot, and others take a reload but so it goes I imagine. Thanks for the help!

**Comment by vovkkk** [comment]
> Kind of odd that some changes apply hot, and others take a reload

There are several possible reasons for that, one of them is possibility to set scheme directly via set method of view’s settings object, i.e. `view.settings().set('color_scheme', 'something')`, some plugins may call this method to provide additional feature for highlighting (SublimeLinter, ColorHighlighter, InactivePanes, and in fact any plugin can call this method), if setting was set directly to view then changes in sublime-settings file(s) will be ignored which in some cases may be useful, but sometimes may seem odd.
