### ISSUE TITLE
table support?

### ISSUE THREAD

**Issue by SS024** [aziz/PlainTasks#293]
Hi developers, thanks for this tool. however notes taking will use table quite often, is there a plan to support table in plaintasks?
not necessary to be html like, but something similar to org-mode with auto-alignment would be great.

thanks
Simon

**Comment by aziz** [comment]
If you need tables and more structured markup support, you'd better check out [PlainNotes](https://github.com/aziz/PlainNotes)

**Comment by vovkkk** [comment]
If you do not want to use PlainNotes and insist on tables in PlainTasks you can hack keybindings (changing context) in your user keybindings file, e.g. if you have SmartMarkdown installed it would be:

```js
	{ "keys": ["tab"], "command": "smart_table",
		"args": {"forward": true}, "context":
		[
			{ "key": "selector", "operator": "equal", "operand": "text.todo notes.todo" },
			{ "key": "preceding_text", "operator": "regex_contains", "operand": "^\\s*(\\||\\+[-=])",
				"match_all": true}
		]
	},
	{ "keys": ["tab"], "command": "smart_table",
		"args": {"forward": true}, "context":
		[
			{ "key": "selector", "operator": "equal", "operand": "text.todo notes.todo" },
			{ "key": "preceding_text", "operator": "regex_contains", "operand": "^\\s*" },
			{ "key": "following_text", "operator": "regex_contains", "operand": "\\s*(\\||\\+[-=])",
				"match_all": true}
		]
	},
	{ "keys": ["shift+tab"], "command": "smart_table",
		"args": {"forward": false}, "context":
		[
			{ "key": "selector", "operator": "equal", "operand": "text.todo notes.todo" },
			{ "key": "preceding_text", "operator": "regex_contains", "operand": "^\\s*(\\||\\+[-=])",
				"match_all": true}
		]
	},
	{ "keys": ["shift+tab"], "command": "smart_table",
		"args": {"forward": false}, "context":
		[
			{ "key": "selector", "operator": "equal", "operand": "text.todo notes.todo" },
			{ "key": "preceding_text", "operator": "regex_contains", "operand": "^\\s*" },
			{ "key": "following_text", "operator": "regex_contains", "operand": "\\s*(\\||\\+[-=])",
				"match_all": true}
		]
	},
```

**Comment by SS024** [comment]
Thanks will try.

? 2016?11?9??02:28?Vova Kolobok <notifications@github.com<mailto:notifications@github.com>> ???


If you do not want to use PlainNotes and insist on tables in PlainTasks you can hack keybindings (changing context) in your user keybindings file, e.g. if you have SmartMarkdown installed it would be:

    { "keys": ["tab"], "command": "smart_table",
        "args": {"forward": true}, "context":
        [
            { "key": "selector", "operator": "equal", "operand": "text.todo notes.todo" },
            { "key": "preceding_text", "operator": "regex_contains", "operand": "^\\s*(\\||\\+[-=])",
                "match_all": true}
        ]
    },
    { "keys": ["tab"], "command": "smart_table",
        "args": {"forward": true}, "context":
        [
            { "key": "selector", "operator": "equal", "operand": "text.todo notes.todo" },
            { "key": "preceding_text", "operator": "regex_contains", "operand": "^\\s*" },
            { "key": "following_text", "operator": "regex_contains", "operand": "\\s*(\\||\\+[-=])",
                "match_all": true}
        ]
    },
    { "keys": ["shift+tab"], "command": "smart_table",
        "args": {"forward": false}, "context":
        [
            { "key": "selector", "operator": "equal", "operand": "text.todo notes.todo" },
            { "key": "preceding_text", "operator": "regex_contains", "operand": "^\\s*(\\||\\+[-=])",
                "match_all": true}
        ]
    },
    { "keys": ["shift+tab"], "command": "smart_table",
        "args": {"forward": false}, "context":
        [
            { "key": "selector", "operator": "equal", "operand": "text.todo notes.todo" },
            { "key": "preceding_text", "operator": "regex_contains", "operand": "^\\s*" },
            { "key": "following_text", "operator": "regex_contains", "operand": "\\s*(\\||\\+[-=])",
                "match_all": true}
        ]
    },

-
