### ISSUE TITLE
accrue @project

### ISSUE THREAD

**Issue by ildarkhasanshin** [aziz/PlainTasks#294]
no space before checkbox incorrectly archived item

![img-2016-10-21-22-02-24](https://cloud.githubusercontent.com/assets/8765305/19606230/65fcbbd2-97da-11e6-8cd2-70d108d428d1.png)
![img-2016-10-21-22-03-01](https://cloud.githubusercontent.com/assets/8765305/19606238/7242f00a-97da-11e6-8ded-4992bff60dcb.png)

"before_tasks_bullet_margin": 0

**Comment by ildarkhasanshin** [comment]
without changes

![img-2016-10-22-01-01-57](https://cloud.githubusercontent.com/assets/8765305/19609921/53ab47f0-97f3-11e6-8df9-d63b56d79a66.png)
![img-2016-10-22-01-02-37](https://cloud.githubusercontent.com/assets/8765305/19609927/598e4046-97f3-11e6-9f1c-ad1b94d6994a.png)

**Comment by vovkkk** [comment]
Uh, I’ve misread your first message.

So you have to indent `test 1` because since it has the same indent level as project it is correctly being considered outside of the project.

`"before_tasks_bullet_margin"` setting is used only during creation of new task.

**Comment by ildarkhasanshin** [comment]
this has its own logic
but it would be more convenient that the objectives of the project come to an end on the first blank line

**Comment by vovkkk** [comment]
I cannot agree in general, although you have a point for first level project, but your suggestion would result in complete disaster in case of elaborate structure of sub-projects, especially starting from level 3-4 I’d assume.

Current implementation is not perfect I admit, and might be even confusing in some cases, but it is comprehensible: as long as task has bigger indent than above project/subproject/separator  it belong to it, if indent is the same or smaller it is not, indent of notes does not matter. And that’s it.
