### ISSUE TITLE
i cant find it

### ISSUE THREAD

**Issue by iiiron** [aziz/PlainTasks#302]
just today.my plaintasks was vanished !
and when i try to install again in sublime text (ctrl + shift + p  >> install  >>  plaintasks)
it find nothing in final step

**Comment by vovkkk** [comment]
If you use any version (in main menu Help→About) of Sublime Text other than 2221, 3125, 3126, then see #300 

Otherwise, exit ST, start it, open console (View→Show Console), wait until text in console stop to be updated, try to install PT, wait for text in console, then paste it here like this:

    ```
    text from console here
    ```

**Comment by iiiron** [comment]
Thank you!  I have fixed it when i clone  source code to Sublime Text packages folder !
