### ISSUE TITLE
eighties-colored theme doesn't support calendar popup

### ISSUE THREAD

**Issue by hedgesky** [aziz/PlainTasks#303]
As screenshot shows, calendar is completely unreadable. Unfortunately, I couldn't find corresponding key in theme files, so without PR for now 😞 

![2016-11-28 19 14 28](https://cloud.githubusercontent.com/assets/3628124/20675925/0b4df83a-b59f-11e6-87a8-7ba3fb1c4055.png)

**Comment by vovkkk** [comment]
Is that colour suitable?

![2016-11-28_23-56-04](https://cloud.githubusercontent.com/assets/1975298/20677664/5b5781f8-b5c6-11e6-9a8a-0ff9cb264005.png)


```diff
--- tasks-eighties-colored.hidden-tmTheme
+++ tasks-eighties-colored.hidden-tmTheme
@@ -14,6 +14,11 @@
 					<key>invisibles</key><string>#EAE3C9</string>
 					<key>lineHighlight</key><string>#464646</string>
 					<key>selection</key><string>#464646</string>
+					<key>popupCss</key>
+					<string><![CDATA[
+						html, body {color: #d3d0c8; background-color: #2d2d2d}
+						a {color: #ACC6F6;}
+					]]></string>
 				</dict>
 			</dict>
 			<dict>
```

**Comment by hedgesky** [comment]
Yes, totally!
