### ISSUE TITLE
User config setting to disable calendar pop-up, "overdue" injected content

### ISSUE THREAD

**Issue by jaacob** [aziz/PlainTasks#304]
I don't see an option in the `.sublime-settings` file to disable the new calendar pop-up and injected "Overdue 3 days" content.

Is this possible?

**Comment by vovkkk** [comment]
> injected "Overdue 3 days" content

`"show_remain_due": false`, it is mentioned in readme.

Disable calendar is not possible yet. I hope to arrange it in near future (this year).

**Comment by jaacob** [comment]
Oops, apologies for the noise. Thanks!

**Comment by vovkkk** [comment]
Disabling calendar is planned, thus the issue must be open yet.

In fact I thankful for reminder, it is not noise.

**Comment by smi11** [comment]
I had a same question as OP and it took me quite a while to find this setting. May I recommend placing "show_remain_due" setting to default config file, that way anyone could see it immediately and use it as needed. I'm also looking forward to disable calendar pop-up setting. Thanks.
