### ISSUE TITLE
Tasks with due date all showing as overdue

### ISSUE THREAD

**Issue by foldedpaper** [aziz/PlainTasks#305]
If I create a new task and give it a due date, e.g.:
```
☐ Read a book @due(Jan 15, 2017 10:00AM)
```
...it highlights in red and shows as 'overdue a little bit', even if it is not overdue or near due within the range set by "highlight_due_soon".

This seems to apply to all tasks with due dates.

Maybe it has something to do with the date format I am using? My setting is:
```
"date_format": "(%b %d, %Y %I:%M%p)"
```

**Comment by vovkkk** [comment]
Could you please uncomment [line 180](https://github.com/aziz/PlainTasks/blob/master/PlainTasksDates.py#L180) in `Packages/PlainTasks/PlainTasksDates.py` and tell me what appear in console (View→Show Console) when you activate your todo tab?

And tell what OS you use and your locale (like English or French, or whatever it is).

**Comment by foldedpaper** [comment]
Sure, console shows:

```
reloading plugin PlainTasks.PlainTasksDates
Special case of short date: less than 2 numbers
Special case of short date: less than 2 numbers
Special case of short date: less than 2 numbers
Special case of short date: less than 2 numbers
Special case of short date: less than 2 numbers
Special case of short date: less than 2 numbers
Special case of short date: less than 2 numbers
Special case of short date: less than 2 numbers
Special case of short date: less than 2 numbers
Special case of short date: less than 2 numbers
Special case of short date: less than 2 numbers
Special case of short date: less than 2 numbers
Special case of short date: less than 2 numbers
Special case of short date: less than 2 numbers
```

Using OSX and English.

**Comment by vovkkk** [comment]
I recommend to remove comma in your date format, because comma cannot be part of tag.
Comma breaks tag so user may type regular text after a tag.

**Comment by foldedpaper** [comment]
Thanks for the quick fix. And thanks for the tip on comma in date format. I didn't realize that was breaking tags.
