### ISSUE TITLE
Calendar must replace parentheses

### ISSUE THREAD

**Issue by diego898** [aziz/PlainTasks#306]
For some reason preason `d` then `tab` causes this strange behavior:

![](https://media.giphy.com/media/3o7TKC0Vq97IONVdGo/giphy.gif)

Also, even after deleting the due date tag and restarting sublime, the remaining text persists?

**Comment by vovkkk** [comment]
This is known issue, and it can be workaround by placing cursor on tag itself, i.e. not within parentheses.
