### ISSUE TITLE
User shortcuts not overriding defaults

### ISSUE THREAD

**Issue by bempelise** [aziz/PlainTasks#316]
I always change the done task shortcut from `Ctrl+d` to `Ctrl+/`, however, when putting the shortcut in the user key bindings it is not working. If I change the default key bindings it works but get overwritten to default after a while (probably due to an update).

I would recommend to default the key binding to `Ctrl+/`. It is more intuitive to comment out a done task, plus it spares `Ctrl+d` to its default usage, i.e. multiple selection which is very handy when selecting multiple tasks with the same tag.

**Comment by vovkkk** [comment]
> however, when putting the shortcut in the user key bindings it is not working

I doubt it; it should work as you expect if put definitions for both Ctrl+d and Ctrl+/ in the user key bindings.



> default the key binding to Ctrl+/

No, d was in use like 4 years now.
Plus d is more intuitive for done, than /.
