### ISSUE TITLE
Reformat Tasks Text

### ISSUE THREAD

**Issue by elarb** [aziz/PlainTasks#321]
Is it possible to reformat tasks? If not, should this feature be added?

**Comment by vovkkk** [comment]
I do not understand what you mean.

**Comment by elarb** [comment]
Basically what I meant was a short-cut to lay out spacing, indents, etc. of the text, to make it look cleaner.

**Comment by vovkkk** [comment]
Indents define belonging of a task to a project(and subprojects), so it is up to user to indent and thus structure a list.
It would not make sense to try to re-indent tasks automatically, ruining the original structure.
