### ISSUE TITLE
Theme: Change Line Height

### ISSUE THREAD

**Issue by oldmankit** [aziz/PlainTasks#324]
I'm trying to create my own theme. I've looked at the built-in themes and can't see any way to change line height, or to add padding between each line. Is this possible? 

(I'm using Sublime Text 3. I've never edited a Sublime Text theme before.)

**Comment by vovkkk** [comment]
Preferences → Package Settings → PlainTasks → Settings - User and 
```js
{
  "font_size": 22,
  "line_padding_top": 10,
  "line_padding_bottom": 10

}
```

**Comment by oldmankit** [comment]
That's perfect. Thank you very much.
