### ISSUE TITLE
Snippet/Completion to recalculate lasted or wasted tags

### ISSUE THREAD

**Issue by FichteFoll** [aziz/PlainTasks#327]
Occasionally I forget to clear (or cancel) a task when I am done with it. If it has a `@started` tag, PlainTasks will calculate the total time spent on the task, but if I have to modify any of the times (e.g. the `@done` timestamp), there is no way to re-calculate the total time spent on a task.

**Comment by vovkkk** [comment]
Well, I’m not sure how this feature would be presented to user. (let’s think and discuss)

But if you are looking for quick fix, there is command to calculate it https://github.com/aziz/PlainTasks/blob/master/PlainTasksDates.py#L348

**Comment by vovkkk** [comment]
I did not awake properly and misread the title of this issue.
So you suggest recalculating whenever user press <kbd>tab</kbd> on done/cancelled task.
Good idea, I’m on it.
