### ISSUE TITLE
Latest commit breaks on Windows?

### ISSUE THREAD

**Issue by geniusupgrader** [aziz/PlainTasks#332]
After the f5194c392c46d9afd48b5a918ce4324943efb36a commit,
the commands from Default.sublime-commands inside the PlainTasks Folder (for example plain_tashs_complete) are not shown in the command palette anymore. And when executed with a keybinding nothing happens. I'm on Windows 10

**Comment by vovkkk** [comment]
It works for me, so I’m closing.
If you are sure it is bug in PT then provide more details about your setup (see #300 if your ST version less than 3126), try to reinstall.

**Comment by geniusupgrader** [comment]
Yep, my Sublime Version was an old one. Forgot to revert to the latest version, after testing something else. Sorry for that.
