### ISSUE TITLE
VSCode Port

### ISSUE THREAD

**Issue by Gander7** [aziz/PlainTasks#335]
I love this project :)
My main editor is slowly moving from sublime to vscode (Please don't jump on me :P).
Are there any plans on a version as a vscode extension?
If not, would you mind if I tried my hand at it? (at some point, possibly never depending on workload)

Love your work :)

**Comment by vovkkk** [comment]
There are some ports (or should we say similar plugins, since they are independent projects) already, including one for VSCode https://github.com/aziz/PlainTasks#plaintasks-for-other-editors

You can try contribute to the existing one or start your own, it is up to you.
