### ISSUE TITLE
"Open in browser" opens in wrong browser

### ISSUE THREAD

**Issue by engelju** [aziz/PlainTasks#349]
**Expected**:

When I hit <kbd>⌘ + shift + u</kbd>, the URL under the cursor should open in my default browser (which is Chrome).

**Actual result**:

URL gets opened in another browser (currently Safari), even though Chrome is set to be my default browser, both via [Chrome](https://support.google.com/chrome/answer/95417?hl=en) and through my macOS settings.

**System info**:

macOS 10.12.5
PlainTasks v2017.06.25.18.38.30 (as shown in Sublime > List Packages)

**Comment by vovkkk** [comment]
I’ve no macOS, so I cannot test it, but it is apparently fixed in 3133 https://github.com/SublimeTextIssues/Core/issues/1280, thus closing.

**Comment by engelju** [comment]
Yup, updating to the newest Sublime Text build (which is 3139 as we speak) [within the dev channel](https://www.sublimetext.com/3dev) fixed this issue. Had to buy a Sublime Text license key to get access to the dev builds, though. But anyways, thanks for your help!
