### ISSUE TITLE
How to disable text correction highlighting?

### ISSUE THREAD

**Issue by vach** [aziz/PlainTasks#358]
Using sublime text 3 latest (newest) build, 
just installed plaintasks, and i see it highlighting incorrect words with red under the word...

How can i disable this? i dont see it in normal sublime tab 
anything that does not have .todo is fine

**Comment by nivir** [comment]
@vach can you please upload a screenshot ?

**Comment by vach** [comment]
it went away after few restarts, i suppose its not the plugin, but  i can attach the screenshot later.
