### ISSUE TITLE
Changed font_face, now there is italic everywhere. 

### ISSUE THREAD

**Issue by dok42** [aziz/PlainTasks#359]
Hello everyone,
In PlainTasks.sublime-settings user file, I've change the font to Iosevka, but now the the Regular style is used only for tags and normal text.

I'm not a fan of Italic style and I did read here other post about how to remove italic.
I just want to know if this is normal behaviour or there is something wrong.
Thank you

edit: did try with Courier Prime, Consolas and Roboto Mono too..
only Roboto Mono does not switch to italic...

**Comment by vovkkk** [comment]
Style is defined in tmTheme file, by default task text is italicised, if it is not then there is a problem related to a font.
So yes it is normal (if you use default unmodified tmTheme file).
