### ISSUE TITLE
Unnecessary Repetition in Due/Time Remaining Underlay

### ISSUE THREAD

**Issue by diego898** [aziz/PlainTasks#361]
When I have a test task, even if Im not on the current line an underlay is shown. If I move my cursor or click on the due tag, I get _another_ underlay (making the total 2) showing me the remaining time. 

![](https://media.giphy.com/media/3ohhwEN54amWX8ZxQI/giphy.gif)

How can I make it so that the underlay is only shown when I click on the due date?

**Comment by vovkkk** [comment]
> How can I make it so that the underlay is only shown when I click on the due date?

Either set `"show_remain_due": false` or remove this setting from user settings file.

**Comment by diego898** [comment]
Even with that setting present, I dont think this is the desired behavior correct?

**Comment by vovkkk** [comment]
Do you mean the case of `"show_remain_due": true`? Sure, that is why I labelled it as minor bug, and I think I fixed it, will push the commit in a minute.

If you mean something else, please be more specific.
