### ISSUE TITLE
Using CTRL+Enter doesn't respect indent size setting.

### ISSUE THREAD

**Issue by dzift** [aziz/PlainTasks#362]
Reproduce steps:
  1. New blank tasks document.
  2. Indent size: 4 spaces. (`"tab_size": 4` in PlainTasks settings)
  3. Using CTRL+Enter uses 2 spaces.

**Comment by vovkkk** [comment]
It is a feature, the indent of new task depends either on indent of current line under cursor or value of `"before_tasks_bullet_margin"` setting.

**Comment by dzift** [comment]
Doh.. Sorry about this.
