### ISSUE TITLE
Sublime build3145 causes task text to appear dimmed / greyed out

### ISSUE THREAD

**Issue by ronjouch** [aziz/PlainTasks#363]
With [Dev Build 3145](http://www.sublimetext.com/3dev), tasks appear gray/dimmed:

![plaintasks_subl-3145-fs8](https://user-images.githubusercontent.com/522085/31258950-09cb01d0-aa11-11e7-89aa-d4b9d73acf11.png)

Whereas Build 3144 correctly displayed tasks text in black:

![plaintasks_subl-3144-fs8](https://user-images.githubusercontent.com/522085/31258961-2090aa32-aa11-11e7-8037-c6ee95ba1db4.png)

Config: Arch Linux, Plaintasks up-to-date from PackageControl as of 2017-10-05

**Comment by ronjouch** [comment]
Thanks @vovkkk 👍. But after updating PlainTasks through PackageControl, Tasks files are now no longer yellow-styled, they seem to follow my color scheme. For example, with Monokai,

![selection_001](https://user-images.githubusercontent.com/522085/31276150-65b6cfd6-aa68-11e7-9086-abfa64e1336a.png)

Is it expected?

**Comment by vovkkk** [comment]
Try to re-open a file, or execute in console `view.settings().erase('color_scheme')`.

PC removes package on upgrade, and thus set global scheme to avoid error message, it should set the previous scheme back when upgrade is finished, but I guess something prevented it in your case (it might be another package or unfortunate circumstances).

**Comment by ronjouch** [comment]
> *Try to re-open a file, or execute in console `view.settings().erase('color_scheme')`.*

@vovkkk worked, thanks! Yeah I noticed PC removes package on upgrade; usually it means a flickering of (unstyled) PlainTasks file, then the style is re-applied on install, but like you said this time it seems to have failed.
