### ISSUE TITLE
Lines with text that starts with a dash counts as a task

### ISSUE THREAD

**Issue by michaelgarde** [aziz/PlainTasks#365]
For example:
```
☐ My task
   - Personal note
   - http://google.com
```
The above will list as three tasks and not as one as i would personally expect. I would have thought that a line that starts with a dash would be considered an item in a list in the same way as Markdown does. Using an asterix as a bullet works but isn't as pretty as a dash in my opinion.

**Comment by vovkkk** [comment]
PlainTasks supports different bullets, and they work in the same time—this is one of the core features. Moreover, highlighting (i.e. syntax definitions) is static, it is not that easy to change syntax definitions on the fly, so it is not only the core feature (i.e. what we want to have), but it is the normal way as syntax highlighting works in ST.
Also dash (or hyphen) is crucial for compatibility with TaskPaper—another important feature of PlainTasks.

The best bullet for a list item is `•`, or you can use `−` (minus); which can be easily typed with some sort of typographical keyboard layout (you can easily find a bunch on internet or, perhaps, you already have one in your OS).

**Comment by michaelgarde** [comment]
When I say dash i consider it synonymous with the minus character. This isn't technically correct, so I apologies for the confusion. 

> The best bullet for a list item is •, or you can use − (minus); 

The point of my original post was to note that i would expect * (asterix), - (minus) and + (plus) all to act as an unordered list, (not as a task) as is often the case in other notations. [Markdown](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#lists) is such an example. 

However
![image](https://user-images.githubusercontent.com/6233262/31988637-1319ca1e-b970-11e7-9a0e-fed9e74091f9.png)

I didn't know about taskpaper before, so if this is the adopted semantic, then it is just a design decision, it just originally seemed counter-intuitive to me, that -, * and + each have their own semantic. In the above example, i would originally have expected the status bar to state 0/1 done.

**Comment by vovkkk** [comment]
I understood your point, and tried to explain that optional bullets (you can see them in default settings file) all are affecting the role of a corresponding line in a document regardless of which bullets are set as default for corresponding actions.

It is not minus on your screenshot:

![2017-10-25_16-15-31](https://user-images.githubusercontent.com/1975298/31990601-c77885b6-b99f-11e7-89e5-6239f27f26cd.png)

Plus sign is an optional done bullet, so user may avoid Unicode in a document (sometimes it maybe necessary, sometimes it is just aesthetics)
![2017-10-25_16-33-11](https://user-images.githubusercontent.com/1975298/31991537-34a9c7f6-b9a2-11e7-9e29-b83ab0455385.png)

**Comment by michaelgarde** [comment]
I see. I had not thought about looking in the settings file. Can these be customized, such that - (as well as variations) and + are no longer considered tasks?

So when i push the key on my keyboard it generates a hyphen it seems. I have always thought that it was a minus character, in fact, i do not think i have ever considered them to be different. I am getting smarter everyday. 
I think i now understand what you mean. A [true minus character](https://en.wikipedia.org/wiki/Plus_and_minus_signs#Minus_sign) does indeed generate an item in an unordered bullet list . Unfortunately my keyboard layout (danish) only generates hyphens (including the numpad "minus").

Anyway, no matter how you draw a short vertical line with similarity to a -, i still would expect it to be an item unordered bullet list. But now i know that PlainTasks was designed this way, which is fine. I initially just thought it was a bug.

I hope you do not get me wrong. I love this plugin and use it on a daily basis for work as well as personal. I usually have Sublime Text open for writing notes anyway, so PlainTasks supports my workflow in a positive way.

**Comment by vovkkk** [comment]
> Can these be customized, such that - (as well as variations) and + are no longer considered tasks?

It can be achieved, but I already explained in previous messages why it is not going to happen.
We may reconsider this matter in case of reliable and simple way to modify syntax definitions on the fly.

> Unfortunately my keyboard layout (danish) only generates hyphens (including the numpad "minus").

If you are on Windows, you can use [Microsoft Keyboard Layout Creator](https://www.microsoft.com/en-us/download/details.aspx?id=22339) to make a custom layout; you can load an existing layout from File menu to simplify the process of creation.

If you’re on Mac or Linux, there are built-in ways to type all kinds of symbols.

**Comment by michaelgarde** [comment]
> We may reconsider this matter in case of reliable and simple way to modify syntax definitions on the fly.

That would actually be a cool feature, as each user could then define their own syntax or one that is based on a well know syntax. Even something as json, xml og csv could be supported at some point i suppose.

> If you are on Windows, you can use Microsoft Keyboard Layout Creator to make a custom layout; you can load an existing layout from File menu to simplify the process of creation.
> 
> If you’re on Mac or Linux, there are built-in ways to type all kinds of symbols.

Well that is just an awkward work-around really.
