### ISSUE TITLE
Due tag auto complete date alternates between mm/dd/yy and dd/mm/yy formats

### ISSUE THREAD

**Issue by 5vbz3r0** [aziz/PlainTasks#371]
When adding a @due tag, the date is added in mm/dd/yy format. So, pressing tab after @due(04-01-18) sets the due date as 01-04-18. So, it becomes @due(01-04-18). Pressing tab from within the tag again, now sets it as @due(04-01-18). Fortunately, this doesn't happen with dates larger than 12 for obvious reasons.
I know it sounds confusing, but I've tried to describe it as best as I can.
![image](https://user-images.githubusercontent.com/10692309/34722477-17f24406-f56d-11e7-9bbf-ff261c50a707.png)
![image](https://user-images.githubusercontent.com/10692309/34722517-46fc59ee-f56d-11e7-9c1d-6fa528e5fe35.png)

Also, as you can see, overdue task highlighting works now and then (or not at all), but that probably is a different issue.

**Comment by vovkkk** [comment]
How your date format looks? 
Which version of ST? 
Try to run *Package Control: Satisfy dependencies* command in command palette.

`"date_format": "(%m-%d-%y %H:%M)",`:

![2018-01-09_23-27-07](https://user-images.githubusercontent.com/1975298/34731338-a570e680-f594-11e7-993d-2f13a5ad983d.png)

![2018-01-09_23-28-58](https://user-images.githubusercontent.com/1975298/34731426-e5a32b82-f594-11e7-9aab-4785edef0808.png)
