### ISSUE TITLE
Trouble Customizing Theme

### ISSUE THREAD

**Issue by hearsay1423** [aziz/PlainTasks#379]
I would like to customize the tags @critical @high @low @today to any name. I successfully changed the information in the following:

```
<dict>
	<key>name</key>
	<string>customname</string> <!-- add a custom name -->
	<key>scope</key>
	<string>string.other.tag.todo.customname</string>
	<key>settings</key>
	<dict>
		<key>background</key>
		<string>#666600</string><!--customize the background-->
		<key>foreground</key>
		<string>#ffffff</string> <!--customize the foreground-->
		<key>fontStyle</key>
		<string>bold</string>
	</dict>
```

But this does not work. Can you help me customize my own tags using words of my choosing such as @customname

Thank you.

**Comment by vovkkk** [comment]
You have to change syntax definitions, there are tmLanguage for ST2 and sublime-syntax for ST3 files, keep in mind that if PT will be updated then you’ll lose your changes.
