### ISSUE TITLE
[Feature Request] Configure timestamp visibility

### ISSUE THREAD

**Issue by ErnestUTN** [aziz/PlainTasks#390]
Greetings

First of all, Let me say I love your plugin, so keep up the good job.
Second, I would like to customise timestamp visibility(true | false) in the config files when you mark tasks as done,cancelled,etc since sometimes they might not be necessary at all, but still want to keep the rest of the functionality.

Regards

**Comment by vovkkk** [comment]
We cannot toggle visibility of a text, we could fold it I guess but it would be too bizarre folding only a part of a line.

If you want to define whether a timestamp has to be inserted upon a completing then use `"done_date": false` setting, all settings are documented in the readme btw.

If you want to toggle a setting often you can make a keybinding like this:

```
{"keys": ["f1"], "command": "toggle_setting", "args": {"setting": "done_date"}}
```

**Comment by ErnestUTN** [comment]
Thanks! That will do. Sry about not searching it in the Readme.. I had just looked in the config ini for that setting.
