### ISSUE TITLE
red triangle thingy in side bar?

### ISSUE THREAD

**Issue by benblo** [aziz/PlainTasks#394]
I just noticed this:
![image](https://user-images.githubusercontent.com/574187/54348802-16780780-464a-11e9-906a-b6cd6cd0fcb5.png)
(I'm pretty sure "side bar" is not the right name for that part of the editor, but I don't know what is.)

I think it's since Sublime's recent update (3.2, build 3200). I don't know if it's PlainTasks-specific or if it happens in all of Sublime, as I mostly use it for PlainTasks :) (which is awesome, btw), so I haven't had a chance to notice it in regular files yet.
Any idea what causes this? I don't understand the pattern, sometimes I have this triangle on a few lines, then not for a few lines, then again...

**Comment by EvilKhaosKat** [comment]
>Any idea what causes this? I don't understand the pattern, sometimes I have this triangle on a few lines, then not for a few lines, then again...
Does that todo file lie within git repository?
Usually that arrow marks removed line(s) in terms of git

**Comment by benblo** [comment]
Ah you're right, it could be the first time I've versioning a .todo file! Thanks!
