### ISSUE TITLE
Installation dependency-problem in Sublime Text 4 ?

### ISSUE THREAD

**Issue by ijzerbroot** [aziz/PlainTasks#417]
Hello!

i am unable to install PlainTasks in Sublime Text 4 (the beta; currently 4099).
Apparently the dateutil dependency cannot be installed.

messages:
```
Package Control: The dependency 'dateutil' is not currently installed; installing...
Package Control: The dependency 'dateutil' is not available
Package Control: The dependency 'dateutil' could not be installed or updated
```

Is this a known problem or am I simply not doing it right ?

**Comment by vovkkk** [comment]
Confirm https://github.com/wbond/package_control/issues/1558#issue-848134295

**Comment by vovkkk** [comment]
Meanwhile you can install it by hand:

* Download dependency https://github.com/vovkkk/sublime-dateutil/archive/refs/heads/master.zip

* Unpack, rename and drop to `Packages` so directories will look like this:  

        ▾ Packages\
            ▾ dateutil\
                ▸ all\
                ≡ readme.md

* In ST command palette run command `PC: Install local dependency`

**Comment by ijzerbroot** [comment]
Much appreciated! 
Thank you for your superfast response!
