### ISSUE TITLE
Autocomlete on s produce sftp instead @started(21-10-29 14:50)

### ISSUE THREAD

**Issue by gudata** [aziz/PlainTasks#428]
Hello,
Probably it is something simple, but I can't figure out how to make the ```s tab tab``` to start a task.
Instead the first item of the autocomplete is selected.

If I want to add the started tag I have to s tab, 10xDOWN_KEY, selected "s" snippet, press tab one more time.

![Menu_002](https://user-images.githubusercontent.com/25951/139430272-20c83693-561c-4770-b3a4-e41e3710cc6c.png)
Is there solution to return ```s tab tab``` behaviour?

**Comment by vovkkk** [comment]
As far as I know there is no solution if you are using ST4.

Closing as dup of #420
