### ISSUE TITLE
Broken for Windows 11 / Sublime Text 4? Hotkeys not working

### ISSUE THREAD

**Issue by selvex** [aziz/PlainTasks#435]
Hi, huge fan of the package. Have been using it daily for years.

Sadly, my PC broke and today I reinstalled Sublime Text - apparently we are at version 4 now, while I was stuck at 3 for a _while_.

Downloaded PlainTasks and no shortcuts are working. `CTRL + Enter` doesn't create new tasks, `CTRL+D` doesn't finish them (it triggers Sublime Text default hotkey which is "select current word")

Not sure if I am doing something wrong or if it's a general problem.
Would love some insight since this tool is an integral part of my daily work and it would be a shame to replace it.

**Comment by m3taphysics** [comment]
I have the same issue in windows 10, Build 4169

**Comment by vovkkk** [comment]
Works for me.

For you, it is probably conflict with another package, or may be just a glitch.
First, try to restart ST, or re-open file, or create a new tasks document via command palette.
Second, to check any conflicts; you can see which commands are triggered by the key strokes: open console <kbd>Ctrl</kbd>+<kbd>\`</kbd>, type `sublime.log_commands(True)`.
