### ISSUE TITLE
some suggestions

### ISSUE THREAD

**Issue by leecade** [aziz/PlainTasks#9]
First of all, this plugin is Awesome, thanks

--- ✄ -----------------------

todo:
 ☐ supports url link (highlight & click to open?)
 ☐ ⌘ + Enter ==> add project title is better?
 ☐ After archive the done task, I don't know which project is it belongs to, how about this:

```
 title1:
 ☐ task1
 title2:
 ☐ task2
```

archive

```
 ✔ title1: task1 @done (12-09-18 00:07)
 ✔ title2: task2 @done (12-09-18 00:07)
```

**Comment by JimmyLv** [comment]
Hey! any update on the archived task with the project name?
